/* ============================================================
   CUMBRE — Module « Traduire » : extension (FR → ES)
   Même structure que translations.js. Objectifs :
   - étoffer chaque thème existant (3 → ~10 phrases)
   - combler les deux trous : « Verbos & régime » et « Nuances C2 »
     (mappés à des leçons mais sans aucune phrase auparavant)
   ============================================================ */
window.TRANSLATIONS = window.TRANSLATIONS.concat([

  /* --- Ser / Estar --- */
  { fr:"El es de Séville, mais il vit à Madrid depuis dix ans.", en:"Él es de Sevilla, pero vive en Madrid desde hace diez años.", alt:["Es sevillano, pero vive en Madrid desde hace diez años."], cat:"Ser/Estar", point:"ser (origine) vs vivre", note:"Origine → ser : « es de Sevilla ». « desde hace + durée » = depuis (durée écoulée).", level:"A2" },
  { fr:"La réunion est dans la salle du fond.", en:"La reunión es en la sala del fondo.", alt:["La reunión tiene lugar en la sala del fondo."], cat:"Ser/Estar", point:"ser (lieu d'un événement)", note:"Piège classique : un ÉVÉNEMENT « a lieu » → ser, pas estar. « La fiesta es en mi casa », mais « el objeto está en mi casa ».", level:"B1" },
  { fr:"Ces pommes ne sont pas encore mûres.", en:"Estas manzanas todavía no están maduras.", alt:["Estas manzanas aún no están maduras."], cat:"Ser/Estar", point:"estar (état changeant)", note:"« estar verde/maduro » = pas mûr / mûr (état). « ser verde » = vert (couleur). Ici c'est l'état → estar.", level:"B1" },
  { fr:"Mon grand-père est très vif malgré son âge.", en:"Mi abuelo es muy espabilado a pesar de su edad.", alt:["Mi abuelo es muy listo a pesar de la edad."], cat:"Ser/Estar", point:"ser listo vs estar listo", note:"« ser listo » = être malin (trait). « estar listo » = être prêt (état). Ici : trait de caractère → ser.", level:"B2" },
  { fr:"Le café est froid, je ne vais pas le boire.", en:"El café está frío, no me lo voy a tomar.", alt:["El café está frío, no voy a tomármelo."], cat:"Ser/Estar", point:"estar (état) + pronoms", note:"Température ressentie = état → está frío. « tomárselo » : pronoms accrochés à l'infinitif ou devant l'auxiliaire.", level:"B1" },
  { fr:"Nous sommes en train de préparer le dîner.", en:"Estamos preparando la cena.", alt:["Estamos haciendo la cena."], cat:"Ser/Estar", point:"estar + gérondif (progressif)", note:"Action en cours → estar + gérondif. Jamais « somos preparando ».", level:"A2" },
  { fr:"Le problème, c'est qu'il n'y a plus de temps.", en:"El problema es que ya no hay tiempo.", alt:["Lo que pasa es que ya no queda tiempo."], cat:"Ser/Estar", point:"ser (définition) + hay", note:"Définir / identifier → ser : « es que ». « ya no hay » = il n'y a plus. « hay » est invariable.", level:"B1" },

  /* --- Gustar & pronoms --- */
  { fr:"Nous manquons de temps pour tout finir.", en:"Nos falta tiempo para terminarlo todo.", alt:["No nos da tiempo a terminarlo todo."], cat:"Gustar & pronoms", point:"faltar (construction comme gustar)", note:"« faltar » marche comme gustar : « nos falta tiempo » (le temps nous manque). Le sujet est « tiempo ».", level:"B1" },
  { fr:"Ça m'est égal, choisis toi.", en:"Me da igual, elige tú.", alt:["Me da lo mismo, elige tú."], cat:"Gustar & pronoms", point:"dar igual + impératif", note:"« me da igual » = ça m'est égal (structure type gustar). « elige tú » : le pronom sujet renforce.", level:"B1" },
  { fr:"Il leur reste seulement deux jours de vacances.", en:"Solo les quedan dos días de vacaciones.", alt:["Les quedan solo dos días de vacaciones."], cat:"Gustar & pronoms", point:"quedar (comme gustar, accord pluriel)", note:"« quedar » type gustar : le verbe s'accorde à « dos días » (pluriel) → quedan.", level:"B1" },
  { fr:"Ce film m'a fait très peur.", en:"Esta película me dio mucho miedo.", alt:["Esta peli me dio muchísimo miedo."], cat:"Gustar & pronoms", point:"dar miedo (indefinido)", note:"« dar miedo » = faire peur (type gustar). Au passé ponctuel → dio.", level:"B1" },
  { fr:"Passe-le-moi, s'il te plaît.", en:"Pásamelo, por favor.", alt:["¿Me lo pasas, por favor?"], cat:"Gustar & pronoms", point:"double pronom sur impératif", note:"Impératif affirmatif : pronoms accrochés, COI + COD → « pása-me-lo ». Accent écrit obligatoire (pásamelo).", level:"B2" },
  { fr:"À elle, ça ne l'intéresse pas du tout.", en:"A ella no le interesa nada.", alt:["A ella eso no le interesa en absoluto."], cat:"Gustar & pronoms", point:"interesar + « a ella » redondant", note:"« interesar » type gustar. « A ella » clarifie, mais « le » reste obligatoire. « no… nada » = pas du tout.", level:"B1" },
  { fr:"Le paquet ? Je le leur ai déjà envoyé.", en:"¿El paquete? Ya se lo mandé.", alt:["Ya se lo envié, el paquete."], cat:"Gustar & pronoms", point:"le+lo → se lo", note:"Règle d'or : « le/les » + « lo/la » devient « se lo/la ». Jamais « le lo ». Ici « se lo mandé ».", level:"B2" },

  /* --- Le passé --- */
  { fr:"Pendant qu'elle lisait, quelqu'un a frappé à la porte.", en:"Mientras leía, alguien llamó a la puerta.", alt:["Mientras ella leía, llamaron a la puerta."], cat:"Passé", point:"imperfecto (cadre) + indefinido (rupture)", note:"Le décor en cours → imperfecto (leía) ; l'action qui surgit → indefinido (llamó). C'est LE contraste clé.", level:"B1" },
  { fr:"Je n'ai jamais été en Argentine.", en:"Nunca he estado en Argentina.", alt:["No he estado nunca en Argentina."], cat:"Passé", point:"pretérito perfecto (expérience de vie)", note:"Expérience jusqu'à maintenant, sans date → perfecto : « he estado ». « nunca » avant le verbe permet de sauter le « no ».", level:"B1" },
  { fr:"Ce matin, je me suis levé à six heures.", en:"Esta mañana me he levantado a las seis.", alt:["Esta mañana me levanté a las seis."], cat:"Passé", point:"perfecto (« esta mañana » = journée en cours)", note:"En Espagne, période incluant maintenant (« esta mañana », « hoy ») → perfecto. En Amérique, l'indefinido domine.", level:"B1" },
  { fr:"Quand je suis arrivé, la fête avait déjà commencé.", en:"Cuando llegué, la fiesta ya había empezado.", alt:["Cuando llegué, ya había empezado la fiesta."], cat:"Passé", point:"pluscuamperfecto (antériorité)", note:"Action antérieure à une autre action passée → pluscuamperfecto : « había empezado ». Le passé du passé.", level:"B2" },
  { fr:"Nous avons vécu à Valence pendant cinq ans.", en:"Vivimos en Valencia durante cinco años.", alt:["Estuvimos viviendo en Valencia cinco años."], cat:"Passé", point:"indefinido (période fermée et finie)", note:"Durée délimitée et terminée → indefinido : « vivimos ». Le fait est clos, on n'y vit plus.", level:"B1" },
  { fr:"Il faisait froid et il n'y avait personne dans la rue.", en:"Hacía frío y no había nadie en la calle.", alt:["Hacía frío y la calle estaba vacía."], cat:"Passé", point:"imperfecto (description d'ambiance)", note:"Décor, météo, description → imperfecto : « hacía », « había ». Pas d'action, juste le tableau.", level:"B1" },
  { fr:"Elle m'a dit qu'elle viendrait le lendemain.", en:"Me dijo que vendría al día siguiente.", alt:["Me dijo que iba a venir al día siguiente."], cat:"Passé", point:"condicional = futur du passé", note:"Style indirect : « vendrá » (futur) devient « vendría » (conditionnel) quand le verbe introducteur est au passé.", level:"B2" },

  /* --- Futur / Conditionnel --- */
  { fr:"Il sera à peu près huit heures maintenant.", en:"Serán las ocho más o menos ahora.", alt:["Serán sobre las ocho ahora."], cat:"Futur/Conditionnel", point:"futur de probabilité", note:"Le futur exprime une hypothèse sur le PRÉSENT : « serán las ocho » = il doit être huit heures. Très fréquent à l'oral.", level:"B2" },
  { fr:"À ta place, je ne dirais rien.", en:"Yo que tú, no diría nada.", alt:["En tu lugar, no diría nada."], cat:"Futur/Conditionnel", point:"conditionnel (conseil)", note:"« Yo que tú + conditionnel » = à ta place… « diría » (dire est irrégulier : dir-). « no… nada ».", level:"B1" },
  { fr:"Pourriez-vous m'aider un instant ?", en:"¿Podría ayudarme un momento?", alt:["¿Me podría echar una mano un momento?"], cat:"Futur/Conditionnel", point:"conditionnel de politesse", note:"« podría » adoucit la demande (vouvoiement). Pronom accroché : « ayudar-me » ou « me podría ayudar ».", level:"A2" },
  { fr:"Nous devrions partir avant qu'il ne pleuve.", en:"Deberíamos irnos antes de que llueva.", alt:["Tendríamos que irnos antes de que llueva."], cat:"Futur/Conditionnel", point:"conditionnel + antes de que + subj.", note:"« deberíamos » = nous devrions (conseil). « antes de que » impose le subjonctif → « llueva ».", level:"B2" },
  { fr:"Je te promets que je le ferai demain sans faute.", en:"Te prometo que lo haré mañana sin falta.", alt:["Te juro que lo haré mañana sin falta."], cat:"Futur/Conditionnel", point:"futuro simple (promesse)", note:"Engagement ferme → futur : « haré » (hacer irrégulier : har-). « sin falta » = sans faute.", level:"B1" },
  { fr:"Que feras-tu quand tu finiras tes études ?", en:"¿Qué harás cuando termines los estudios?", alt:["¿Qué vas a hacer cuando acabes la carrera?"], cat:"Futur/Conditionnel", point:"futur + cuando + SUBJONCTIF", note:"Piège majeur : « cuando » tourné vers le futur → subjonctif présent (« termines »), jamais futur. La principale, elle, est au futur.", level:"B2" },

  /* --- Por / Para --- */
  { fr:"Merci pour tout ce que tu as fait pour moi.", en:"Gracias por todo lo que has hecho por mí.", alt:["Gracias por todo lo que hiciste por mí."], cat:"Por/Para", point:"por (cause/échange) + por mí (en ma faveur)", note:"« gracias por » (toujours por). « por mí » ici = en ma faveur, à cause de moi. « lo que » = ce que.", level:"A2" },
  { fr:"Ce cadeau est pour ta mère.", en:"Este regalo es para tu madre.", alt:["Este regalo es para tu mamá."], cat:"Por/Para", point:"para (destinataire)", note:"Destinataire, but → para : « para tu madre ». Règle simple : para = flèche vers une destination/un but.", level:"A2" },
  { fr:"Nous avons payé cinquante euros pour les billets.", en:"Pagamos cincuenta euros por las entradas.", alt:["Pagamos cincuenta euros por los billetes."], cat:"Por/Para", point:"por (prix, échange)", note:"Échange, prix payé → por. « pagar por algo ». « entradas » = billets de spectacle ; « billetes » = billets d'avion/train/banque.", level:"B1" },
  { fr:"Pour un débutant, tu joues vraiment bien.", en:"Para ser principiante, tocas muy bien.", alt:["Para ser un principiante, tocas la mar de bien."], cat:"Por/Para", point:"para (comparaison inattendue)", note:"« para ser + X » = pour un X (contraste, malgré). Nuance très idiomatique et fréquente à l'écrit.", level:"B2" },
  { fr:"Le train passe par Saragosse.", en:"El tren pasa por Zaragoza.", alt:["El tren va por Zaragoza."], cat:"Por/Para", point:"por (lieu de passage)", note:"Traversée, lieu de passage → por : « pasa por ». Para indiquerait la destination finale, pas le trajet.", level:"A2" },
  { fr:"Il faut rendre le devoir pour vendredi.", en:"Hay que entregar el trabajo para el viernes.", alt:["Se tiene que entregar el trabajo para el viernes."], cat:"Por/Para", point:"para (échéance)", note:"Date limite, échéance → para : « para el viernes » (au plus tard vendredi). « hay que + infinitif » = il faut.", level:"B1" },

  /* --- Subjonctif --- */
  { fr:"Je ne crois pas que ce soit une bonne idée.", en:"No creo que sea buena idea.", alt:["No me parece que sea buena idea."], cat:"Subjonctif", point:"subj. après opinion NÉGATIVE", note:"« creo que » + indicatif ; mais « NO creo que » + subjonctif → « sea ». La négation injecte le doute.", level:"B1" },
  { fr:"Je cherche quelqu'un qui sache parler chinois.", en:"Busco a alguien que sepa hablar chino.", alt:["Busco a una persona que sepa chino."], cat:"Subjonctif", point:"subj. (antécédent indéfini/inexistant)", note:"On cherche une personne non identifiée → subjonctif : « que sepa ». Si elle existait précisément : « que sabe ».", level:"B2" },
  { fr:"Reste ici jusqu'à ce que je revienne.", en:"Quédate aquí hasta que vuelva.", alt:["Espérate aquí hasta que yo vuelva."], cat:"Subjonctif", point:"hasta que + subj. (futur)", note:"« hasta que » orienté vers le futur → subjonctif : « vuelva ». « quédate » : impératif + pronom.", level:"B1" },
  { fr:"C'est dommage que tu ne puisses pas venir.", en:"Es una pena que no puedas venir.", alt:["Qué pena que no puedas venir."], cat:"Subjonctif", point:"subj. après jugement/émotion", note:"« es una pena que », « me alegro de que »… (émotion, jugement) → subjonctif : « puedas ».", level:"B1" },
  { fr:"Quoi que tu dises, je ne changerai pas d'avis.", en:"Digas lo que digas, no cambiaré de opinión.", alt:["Digas lo que digas, no voy a cambiar de idea."], cat:"Subjonctif", point:"structure « X lo que X » (concession)", note:"Redoublement au subjonctif = quoi que… : « digas lo que digas », « pase lo que pase ». Concession idiomatique C1.", level:"C1" },
  { fr:"Je te le dis pour que tu sois au courant.", en:"Te lo digo para que estés al tanto.", alt:["Te lo digo para que lo sepas."], cat:"Subjonctif", point:"para que + subj. (but)", note:"« para que » (but, deux sujets différents) → subjonctif : « estés ». Si même sujet : « para + infinitif ».", level:"B2" },
  { fr:"J'espère qu'ils arriveront à l'heure.", en:"Espero que lleguen a tiempo.", alt:["Ojalá lleguen a tiempo."], cat:"Subjonctif", point:"esperar que + subj.", note:"« esperar que » (souhait) → subjonctif : « lleguen ». « a tiempo » = à temps. « ojalá + subj. » = pourvu que.", level:"B1" },

  /* --- Hypothèse C1 --- */
  { fr:"Si nous étions partis plus tôt, nous n'aurions pas raté le vol.", en:"Si hubiéramos salido antes, no habríamos perdido el vuelo.", alt:["Si hubiésemos salido antes, no habríamos perdido el vuelo."], cat:"Hypothèse C1", point:"3e conditionnelle (passé irréel)", note:"Regret sur le passé : « si + pluscuamperfecto du subj. (hubiéramos salido), conditionnel composé (habríamos perdido) ». « perder el vuelo » = rater l'avion.", level:"C1" },
  { fr:"Si tu m'écoutais, tu ne ferais pas ces erreurs.", en:"Si me hicieras caso, no cometerías esos errores.", alt:["Si me escucharas, no cometerías esos errores."], cat:"Hypothèse C1", point:"2e conditionnelle (présent irréel)", note:"Hypothèse improbable au présent : « si + imparfait du subj. (hicieras), conditionnel simple (cometerías) ». « hacer caso » = écouter/tenir compte.", level:"B2" },
  { fr:"Comme si de rien n'était, il a continué à parler.", en:"Como si nada, siguió hablando.", alt:["Como si tal cosa, siguió hablando."], cat:"Hypothèse C1", point:"como si + subj. imparfait", note:"« como si » exige TOUJOURS l'imparfait (ou plus-que-parfait) du subjonctif. « como si nada » = comme si de rien n'était. « seguir + gérondif » = continuer à.", level:"C1" },
  { fr:"Même si j'avais de l'argent, je ne l'achèterais pas.", en:"Aunque tuviera dinero, no lo compraría.", alt:["Aun teniendo dinero, no lo compraría."], cat:"Hypothèse C1", point:"aunque + subj. (concession hypothétique)", note:"« aunque + subjonctif » = même si (hypothèse). Avec indicatif (« aunque tengo »), ce serait un fait admis (« bien que »).", level:"C1" },
  { fr:"Si ça ne tenait qu'à moi, on partirait tout de suite.", en:"Si por mí fuera, nos iríamos ahora mismo.", alt:["Si de mí dependiera, nos iríamos ya."], cat:"Hypothèse C1", point:"tournure idiomatique + irréel", note:"« si por mí fuera » = si ça ne tenait qu'à moi. « ahora mismo » = tout de suite. Registre naturel très valorisé à l'oral.", level:"C1" },

  /* --- Impératif --- */
  { fr:"Ne me le dis pas maintenant, je suis occupé.", en:"No me lo digas ahora, estoy ocupado.", alt:["Ahora no me lo digas, que estoy ocupado."], cat:"Impératif", point:"impératif NÉGATIF + pronoms devant", note:"Impératif négatif = subjonctif présent : « no digas ». Les pronoms passent DEVANT (« no me lo digas »). À l'affirmatif ils se collent : « dímelo ».", level:"B1" },
  { fr:"Asseyez-vous, je vous en prie.", en:"Siéntense, por favor.", alt:["Tomen asiento, por favor."], cat:"Impératif", point:"impératif ustedes + pronom", note:"Vouvoiement pluriel (ustedes) : « siéntense » (sentarse). Pronom accroché à l'affirmatif, accent écrit.", level:"B1" },
  { fr:"Fais-moi confiance et ne dis rien à personne.", en:"Fíate de mí y no le digas nada a nadie.", alt:["Confía en mí y no se lo digas a nadie."], cat:"Impératif", point:"impératif affirmatif + négatif ensemble", note:"« fíate » (affirmatif, pronom collé) puis « no digas » (négatif, subj.). Double négation naturelle : « no… nada a nadie ».", level:"B2" },
  { fr:"Allons-y, il se fait tard.", en:"Vámonos, que se hace tarde.", alt:["Venga, vámonos, que se hace tarde."], cat:"Impératif", point:"impératif nosotros (irse)", note:"« vámonos » = allons-nous-en (le -s tombe devant « nos » : vamos+nos → vámonos). « que » ici = car.", level:"B1" },
  { fr:"Prends ton temps, ne te presse pas.", en:"Tómate tu tiempo, no te agobies.", alt:["Con calma, no te agobies."], cat:"Impératif", point:"affirmatif vs négatif, même verbe pronominal", note:"« tómate » (affirmatif, collé) / « no te agobies » (négatif, devant + subj.). « agobiarse » = se stresser.", level:"B1" },

  /* --- Verbos & régime (TROU COMBLÉ) --- */
  { fr:"Je viens de me rendre compte de mon erreur.", en:"Acabo de darme cuenta de mi error.", alt:["Me acabo de dar cuenta de mi error."], cat:"Verbos & régime", point:"acabar de + darse cuenta DE", note:"« acabar de + infinitif » = venir de. « darse cuenta DE » (préposition obligatoire, ≠ français « se rendre compte »).", level:"B1" },
  { fr:"Il a fini par accepter la proposition.", en:"Acabó por aceptar la propuesta.", alt:["Terminó aceptando la propuesta."], cat:"Verbos & régime", point:"acabar por + inf. / acabar + gérondif", note:"« acabar por + infinitif » ou « acabar + gérondif » = finir par. Deux tournures équivalentes à maîtriser.", level:"B2" },
  { fr:"Arrête de te plaindre et mets-toi au travail.", en:"Deja de quejarte y ponte a trabajar.", alt:["Deja de quejarte y empieza a trabajar."], cat:"Verbos & régime", point:"dejar de / ponerse a", note:"« dejar de + inf. » = arrêter de. « ponerse a + inf. » = se mettre à. « quejarse DE » qqch.", level:"B1" },
  { fr:"Je me suis mis à pleurer sans pouvoir m'en empêcher.", en:"Me eché a llorar sin poder evitarlo.", alt:["Me puse a llorar sin poder evitarlo."], cat:"Verbos & régime", point:"echarse a + inf. (déclenchement soudain)", note:"« echarse a + inf. » = se mettre soudain à (llorar, reír, correr). Plus abrupt que « ponerse a ».", level:"B2" },
  { fr:"Tout dépend de ce que tu décides.", en:"Todo depende de lo que decidas.", alt:["Todo depende de lo que tú decidas."], cat:"Verbos & régime", point:"depender DE + lo que + subj.", note:"« depender DE » (préposition). « lo que » + décision future non connue → subjonctif : « decidas ».", level:"B2" },
  { fr:"Il insiste pour tout payer lui-même.", en:"Insiste en pagarlo todo él mismo.", alt:["Se empeña en pagarlo todo él mismo."], cat:"Verbos & régime", point:"insistir EN + inf.", note:"« insistir EN » (pas « para »). « empeñarse en » = s'obstiner à (synonyme plus fort). « él mismo » = lui-même.", level:"B2" },
  { fr:"Elle rêve de voyager dans le monde entier.", en:"Sueña con viajar por todo el mundo.", alt:["Sueña con recorrer el mundo entero."], cat:"Verbos & régime", point:"soñar CON", note:"« soñar CON » algo/hacer algo = rêver de. Piège fréquent : ni « de », ni « a ». « por todo el mundo » = à travers.", level:"B1" },
  { fr:"Je n'arrive pas à m'habituer à ce climat.", en:"No consigo acostumbrarme a este clima.", alt:["No logro acostumbrarme a este clima."], cat:"Verbos & régime", point:"conseguir + inf. / acostumbrarse A", note:"« conseguir/lograr + inf. » = arriver à, réussir à. « acostumbrarse A » algo = s'habituer à.", level:"B1" },

  /* --- Nuances C2 (TROU COMBLÉ) --- */
  { fr:"On dirait qu'il va pleuvoir.", en:"Parece que va a llover.", alt:["Diríase que va a llover."], cat:"Nuances C2", point:"parece que + ind. (impression)", note:"« parece que » + indicatif (constat probable). « diríase que » = registre très littéraire pour « on dirait que ».", level:"B2" },
  { fr:"Il n'a fait que compliquer les choses.", en:"No ha hecho más que complicar las cosas.", alt:["No hizo sino complicar las cosas."], cat:"Nuances C2", point:"no… más que / no… sino (restriction)", note:"« no hacer más que » = ne faire que. Variante soutenue : « no… sino + inf. ». Nuance de restriction élégante.", level:"C1" },
  { fr:"Quant à moi, je préfère m'abstenir.", en:"En cuanto a mí, prefiero abstenerme.", alt:["Por mi parte, prefiero abstenerme."], cat:"Nuances C2", point:"connecteurs de reprise (en cuanto a)", note:"« en cuanto a » = quant à ; « por mi parte » = pour ma part. Charpente d'un écrit argumenté C1-C2.", level:"C1" },
  { fr:"Non seulement il est arrivé en retard, mais en plus il n'a pas prévenu.", en:"No solo llegó tarde, sino que además no avisó.", alt:["No solo llegó tarde, sino que encima no avisó."], cat:"Nuances C2", point:"no solo… sino que además", note:"Corrélation « no solo… sino que (también/además) ». « sino QUE » devant un verbe conjugué (≠ « sino » seul).", level:"C1" },
  { fr:"C'est précisément ce que je voulais dire.", en:"Es justamente lo que quería decir.", alt:["Es precisamente lo que quería decir."], cat:"Nuances C2", point:"lo que (relatif neutre) + emphase", note:"« lo que » = ce que (relatif neutre, sans antécédent). « justamente/precisamente » renforce l'idée.", level:"B2" },
  { fr:"Aussi étrange que cela puisse paraître, c'est vrai.", en:"Por raro que parezca, es verdad.", alt:["Por extraño que parezca, es cierto."], cat:"Nuances C2", point:"por + adj. + que + subj. (concession)", note:"« por + adjectif + que + subjonctif » = aussi… que. Concession soutenue : « por mucho que », « por más que ».", level:"C1" },
  { fr:"Le fait qu'il soit venu prouve son intérêt.", en:"El hecho de que haya venido demuestra su interés.", alt:["El que haya venido demuestra su interés."], cat:"Nuances C2", point:"el hecho de que + subj.", note:"« el hecho de que » + subjonctif (« haya venido »), même pour un fait avéré : la tournure impose le subjonctif.", level:"C1" },
  { fr:"À force d'insister, il a fini par obtenir ce qu'il voulait.", en:"A fuerza de insistir, acabó consiguiendo lo que quería.", alt:["De tanto insistir, acabó consiguiendo lo que quería."], cat:"Nuances C2", point:"a fuerza de + inf. (cause intensive)", note:"« a fuerza de + infinitif » = à force de. « de tanto + inf. » = à force de tant. Cause par répétition, très idiomatique.", level:"C1" },

  /* --- Expressions --- */
  { fr:"Ça n'a rien à voir avec ce dont nous parlions.", en:"No tiene nada que ver con lo que hablábamos.", alt:["No tiene nada que ver con lo que estábamos hablando."], cat:"Expressions", point:"tener que ver con", note:"« tener que ver con » = avoir à voir avec. « lo que » = ce dont (relatif neutre).", level:"B1" },
  { fr:"Petit à petit, il apprend l'espagnol.", en:"Poco a poco, va aprendiendo español.", alt:["Poquito a poco, va aprendiendo español."], cat:"Expressions", point:"ir + gérondif (progression)", note:"« ir + gérondif » = progression graduelle (« il apprend petit à petit »). « poco a poco » renforce.", level:"B1" },
  { fr:"De toute façon, ça ne changera rien.", en:"De todas formas, no cambiará nada.", alt:["De todos modos, no cambiará nada."], cat:"Expressions", point:"connecteurs (de todas formas)", note:"« de todas formas / de todos modos / de todas maneras » = de toute façon. Interchangeables.", level:"B1" },
  { fr:"En fin de compte, tu avais raison.", en:"A fin de cuentas, tenías razón.", alt:["Al fin y al cabo, tenías razón."], cat:"Expressions", point:"locutions de conclusion", note:"« a fin de cuentas », « al fin y al cabo » = en fin de compte, après tout. « tener razón » = avoir raison.", level:"B2" },
  { fr:"Il est arrivé sain et sauf.", en:"Llegó sano y salvo.", alt:["Llegó sano y salvo a casa."], cat:"Expressions", point:"expression figée (sano y salvo)", note:"« sano y salvo » = sain et sauf (s'accorde : « sana y salva »). Doublet figé fréquent.", level:"B1" },
  { fr:"Ça vaut le coup d'essayer.", en:"Vale la pena intentarlo.", alt:["Merece la pena intentarlo."], cat:"Expressions", point:"valer/merecer la pena", note:"« valer la pena » = « merecer la pena » = valoir la peine / le coup. + infinitif ou + que + subj.", level:"B1" }

]);
