/* ============================================================
   CUMBRE — Vocabulaire lot 9 : LES BASES qui manquaient
   [ES, FR, exemple ES, thème, (note affichée au reveal)]
   Le deck était monté vers le C1 en sautant des fondations :
   couleurs, famille, vêtements, animaux, corps, gestes du
   quotidien (frapper, pousser, lancer…), maison, table, météo,
   positions. Tout ce qu'on dit dix fois par jour.
   Chargé APRÈS vocab-es8.js → indices SRS stables (append en fin).
   Les mots perso (Lectura) sont re-décalés au boot : cf app.js.
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  // --- Colores ---
  ["el color", "la couleur", "¿De qué color es tu coche?", "Colores", "Masculin en espagnol : EL color."],
  ["rojo", "rouge", "Llevaba un vestido rojo precioso.", "Colores"],
  ["azul", "bleu", "Tiene los ojos azules.", "Colores", "Même forme au masculin et au féminin : una camisa azul."],
  ["amarillo", "jaune", "Los taxis de Nueva York son amarillos.", "Colores"],
  ["negro", "noir", "Siempre va vestido de negro.", "Colores"],
  ["blanco", "blanc", "Necesito una camisa blanca para la boda.", "Colores"],
  ["gris", "gris", "Hoy el cielo está gris.", "Colores"],
  ["marrón", "marron", "Me he comprado unos zapatos marrones.", "Colores", "Pour les cheveux, on dit castaño (pelo castaño), pas marrón."],
  ["naranja", "orange (couleur)", "El equipo holandés juega de naranja.", "Colores", "Comme adjectif, souvent invariable : unas camisetas naranja. La naranja = le fruit."],
  ["rosa", "rose (couleur)", "Pintaron la habitación de rosa.", "Colores", "Souvent invariable : unos calcetines rosa. La rosa = la fleur."],
  ["morado", "violet", "Tenía los labios morados de frío.", "Colores", "Un moratón = un bleu (sur la peau)."],
  ["azul claro", "bleu clair", "Llevaba una camisa azul claro.", "Colores", "Couleur + claro/oscuro reste invariable : unos pantalones azul oscuro."],
  ["oscuro", "foncé ; sombre", "Prefiero el gris oscuro. / La calle estaba muy oscura.", "Colores"],
  ["dorado", "doré", "Lleva un reloj dorado.", "Colores"],
  ["plateado", "argenté", "Se ha comprado un coche plateado.", "Colores"],
  ["rubio", "blond", "Es rubio y tiene los ojos verdes.", "Colores"],
  ["moreno", "brun ; bronzé", "Es alto y moreno. / Has vuelto muy moreno de la playa.", "Colores", "SER moreno = avoir les cheveux ou la peau bruns ; ESTAR moreno = être bronzé."],
  ["pelirrojo", "roux", "Su hermana pequeña es pelirroja.", "Colores"],
  ["castaño", "châtain", "Tiene el pelo castaño y rizado.", "Colores"],
  ["de colores", "multicolore", "Compró unos globos de colores para la fiesta.", "Colores"],
  ["ponerse rojo", "rougir", "Se puso rojo cuando le preguntaron.", "Colores"],

  // --- Familia ---
  ["el padre", "le père", "Mi padre trabaja en un banco.", "Familia"],
  ["la madre", "la mère", "Mi madre es profesora de inglés.", "Familia"],
  ["los padres", "les parents (père et mère)", "Todavía vivo con mis padres.", "Familia", "Piège : los parientes = la famille au sens large (oncles, cousins…)."],
  ["los parientes", "les proches, la famille élargie", "En Navidad vienen todos los parientes.", "Familia", "≠ los padres (le père et la mère)."],
  ["el hijo", "le fils", "Tienen dos hijos: un chico y una chica.", "Familia", "Los hijos = les enfants (d'un couple), même mixtes."],
  ["la hija", "la fille (enfant de)", "Su hija estudia en Madrid.", "Familia", "La fille au sens « jeune femme » = la chica."],
  ["el marido", "le mari", "Su marido es de Valencia.", "Familia", "Aussi el esposo (plus formel)."],
  ["la mujer", "la femme ; l'épouse", "Te presento a mi mujer, Laura.", "Familia"],
  ["el abuelo", "le grand-père", "Mi abuelo tiene noventa años.", "Familia", "Los abuelos = les grands-parents."],
  ["el tío", "l'oncle ; le mec (fam.)", "Mi tío vive en Argentina. / ¡Qué pasa, tío!", "Familia"],
  ["la tía", "la tante", "Mi tía nos invitó a comer el domingo.", "Familia"],
  ["el primo", "le cousin", "Mis primos vienen a pasar el verano.", "Familia"],
  ["el sobrino", "le neveu", "Le compré un regalo a mi sobrino.", "Familia", "La sobrina = la nièce."],
  ["el nieto", "le petit-fils", "La abuela adora a sus nietos.", "Familia", "Los nietos = les petits-enfants."],
  ["el bebé", "le bébé", "El bebé no ha dormido nada esta noche.", "Familia"],
  ["el hijo único", "l'enfant unique", "Soy hijo único.", "Familia"],
  ["el novio", "le petit ami ; le marié", "Mi hermana viene con su novio.", "Familia", "La novia = la copine ; la mariée."],
  ["criar", "élever (des enfants)", "La criaron sus abuelos.", "Familia", "≠ crear (créer)."],
  ["parecerse a", "ressembler à", "Te pareces mucho a tu padre.", "Familia", "Pronominal : parecerse A alguien. Parecer seul = sembler."],
  ["mayor", "plus âgé ; aîné ; âgé", "Mi hermano mayor tiene treinta años. / Es una señora mayor.", "Familia", "Hermano mayor / menor = frère aîné / cadet."],

  // --- Ropa ---
  ["la camisa", "la chemise", "Plancha la camisa antes de la entrevista.", "Ropa"],
  ["la camiseta", "le t-shirt ; le maillot", "Llevaba una camiseta del Real Madrid.", "Ropa"],
  ["los pantalones", "le pantalon", "Estos pantalones me quedan largos.", "Ropa", "Souvent au pluriel. Me quedan largos = ils sont trop longs pour moi."],
  ["los vaqueros", "le jean", "Siempre voy en vaqueros.", "Ropa"],
  ["la falda", "la jupe", "Llevaba una falda larga.", "Ropa"],
  ["el vestido", "la robe", "Se compró un vestido para la boda.", "Ropa", "≠ vêtement (= la prenda, la ropa)."],
  ["la chaqueta", "la veste", "Coge la chaqueta, que hace fresco.", "Ropa"],
  ["el abrigo", "le manteau", "En invierno necesitas un abrigo.", "Ropa"],
  ["el jersey", "le pull", "Ponte un jersey, que hace frío.", "Ropa"],
  ["los zapatos", "les chaussures", "Quítate los zapatos en casa.", "Ropa"],
  ["las zapatillas", "les baskets ; les chaussons", "Voy a correr con mis zapatillas nuevas.", "Ropa"],
  ["las botas", "les bottes", "Para la montaña, mejor botas.", "Ropa"],
  ["los calcetines", "les chaussettes", "Siempre pierdo un calcetín en la lavadora.", "Ropa"],
  ["la gorra", "la casquette", "Llevaba una gorra para el sol.", "Ropa"],
  ["el sombrero", "le chapeau", "Mi abuelo nunca salía sin sombrero.", "Ropa"],
  ["la bufanda", "l'écharpe", "Ponte la bufanda, que hace mucho frío.", "Ropa"],
  ["los guantes", "les gants", "Los guantes de boxeo pesan más de lo que parece.", "Ropa"],
  ["el cinturón", "la ceinture", "Abróchate el cinturón.", "Ropa", "Abrocharse el cinturón = attacher sa ceinture."],
  ["el traje", "le costume", "Fue a la entrevista con traje y corbata.", "Ropa", "El traje de baño = le maillot de bain."],
  ["la corbata", "la cravate", "No sé hacerme el nudo de la corbata.", "Ropa"],
  ["el bolsillo", "la poche", "Tengo las llaves en el bolsillo.", "Ropa"],
  ["la talla", "la taille (vêtement)", "¿Tiene esta camisa en una talla más?", "Ropa", "Pour les chaussures : ¿Qué número calzas?"],
  ["el bolso", "le sac à main", "Se dejó el bolso en el taxi.", "Ropa", "La mochila = le sac à dos ; la bolsa = le sac (plastique, courses)."],
  ["la mochila", "le sac à dos", "Llevo el portátil en la mochila.", "Ropa"],
  ["ponerse", "mettre (un vêtement)", "Ponte el abrigo antes de salir.", "Ropa", "Quitarse = enlever. Ponerse a + infinitif = se mettre à."],
  ["quitarse", "enlever (un vêtement)", "Quítate la chaqueta, que hace calor.", "Ropa"],
  ["probarse", "essayer (un vêtement)", "¿Puedo probarme estos pantalones?", "Ropa", "Probar = goûter ; probarse = essayer sur soi."],
  ["vestirse", "s'habiller", "Me visto en cinco minutos.", "Ropa", "e→i : me visto, te vistes."],
  ["quedar bien", "aller bien (vêtement)", "Esa chaqueta te queda muy bien.", "Ropa", "Me queda grande / pequeño = c'est trop grand / petit pour moi."],
  ["el anillo", "la bague", "Le regaló un anillo de compromiso.", "Ropa"],
  ["las gafas", "les lunettes", "No veo nada sin gafas.", "Ropa", "Las gafas de sol = les lunettes de soleil."],

  // --- Animales ---
  ["el perro", "le chien", "Saco al perro dos veces al día.", "Animales"],
  ["el caballo", "le cheval", "Montar a caballo me da un poco de miedo.", "Animales", "Montar a caballo = faire du cheval."],
  ["la vaca", "la vache", "Las vacas pastan en el prado.", "Animales"],
  ["el cerdo", "le cochon, le porc", "Esta carne es de cerdo.", "Animales"],
  ["la oveja", "le mouton, la brebis", "Hay muchas ovejas en esta zona.", "Animales"],
  ["la gallina", "la poule", "Tenemos gallinas en el pueblo.", "Animales", "El pollo = le poulet (qu'on mange) ; el gallo = le coq."],
  ["el pájaro", "l'oiseau", "Por la mañana se oyen los pájaros.", "Animales"],
  ["el pez", "le poisson (vivant)", "Tengo dos peces en una pecera.", "Animales", "Le poisson qu'on mange = el pescado. Pluriel : los peces."],
  ["el ratón", "la souris", "Hay un ratón en la cocina.", "Animales", "Aussi la souris d'ordinateur."],
  ["el conejo", "le lapin", "El conejo se escapó de la jaula.", "Animales"],
  ["el oso", "l'ours", "Vimos un oso en los Pirineos.", "Animales"],
  ["el lobo", "le loup", "El lobo ha vuelto a algunas zonas de España.", "Animales"],
  ["el zorro", "le renard", "Un zorro entró en el gallinero.", "Animales"],
  ["el mono", "le singe ; mignon (fam.)", "Los monos del zoo son muy listos. / ¡Qué bebé tan mono!", "Animales"],
  ["la serpiente", "le serpent", "Me dan pánico las serpientes.", "Animales"],
  ["la araña", "l'araignée", "Hay una araña en el techo.", "Animales"],
  ["la mosca", "la mouche", "No paran de entrar moscas por la ventana.", "Animales"],
  ["el mosquito", "le moustique", "Me han picado los mosquitos toda la noche.", "Animales"],
  ["la abeja", "l'abeille", "Las abejas son esenciales para las plantas.", "Animales"],
  ["la hormiga", "la fourmi", "Hay hormigas en el azúcar.", "Animales"],
  ["la tortuga", "la tortue", "Las tortugas pueden vivir más de cien años.", "Animales"],
  ["el pato", "le canard", "Dimos de comer a los patos del parque.", "Animales"],
  ["el toro", "le taureau", "El toro es un símbolo de España.", "Animales"],
  ["la ballena", "la baleine", "Vimos ballenas desde el barco.", "Animales"],
  ["el tiburón", "le requin", "No hay tiburones en esta playa.", "Animales"],
  ["la mascota", "l'animal de compagnie", "¿Tienes mascota?", "Animales"],
  ["ladrar", "aboyer", "El perro del vecino ladra toda la noche.", "Animales"],
  ["picar", "piquer ; grignoter", "Me ha picado una abeja. / ¿Picamos algo?", "Animales"],

  // --- Cuerpo ---
  ["la cara", "le visage", "Lávate la cara.", "Cuerpo", "¡Qué cara tienes! = quel culot !"],
  ["el pelo", "les cheveux", "Tiene el pelo largo.", "Cuerpo", "Singulier collectif : tengo el pelo corto. Aussi un poil."],
  ["la nariz", "le nez", "Me sangra la nariz.", "Cuerpo"],
  ["la boca", "la bouche", "No hables con la boca llena.", "Cuerpo"],
  ["el diente", "la dent", "Me duele un diente.", "Cuerpo", "Lavarse los dientes = se brosser les dents. La muela = la molaire."],
  ["la lengua", "la langue (organe et idiome)", "Me mordí la lengua. / Hablo tres lenguas.", "Cuerpo"],
  ["la oreja", "l'oreille", "Tiene las orejas pequeñas.", "Cuerpo", "El oído = l'ouïe, l'oreille interne : me duele el oído."],
  ["el cuello", "le cou ; le col", "Me duele el cuello de dormir mal.", "Cuerpo"],
  ["el hombro", "l'épaule", "Me he hecho daño en el hombro.", "Cuerpo", "Hacerse daño = se faire mal."],
  ["el pecho", "la poitrine, le torse", "Siento un dolor en el pecho.", "Cuerpo"],
  ["la barriga", "le ventre", "Me duele la barriga.", "Cuerpo", "Aussi la tripa (fam.), el vientre (soutenu)."],
  ["el dedo", "le doigt", "Me he cortado el dedo.", "Cuerpo", "El dedo del pie = l'orteil."],
  ["la uña", "l'ongle", "Deja de morderte las uñas.", "Cuerpo"],
  ["la rodilla", "le genou", "Me lesioné la rodilla jugando al fútbol.", "Cuerpo"],
  ["el pie", "le pied", "Fuimos a pie.", "Cuerpo", "A pie = à pied ; de pie = debout."],
  ["el tobillo", "la cheville", "Me torcí el tobillo.", "Cuerpo"],
  ["la muñeca", "le poignet ; la poupée", "Llevo el reloj en la muñeca izquierda.", "Cuerpo"],
  ["el codo", "le coude", "Quita los codos de la mesa.", "Cuerpo"],
  ["la piel", "la peau", "Tiene la piel muy blanca.", "Cuerpo"],
  ["el corazón", "le cœur", "El corazón me latía a mil.", "Cuerpo"],
  ["la sangre", "le sang", "No soporto ver sangre.", "Cuerpo", "Féminin en espagnol : la sangre."],
  ["el hueso", "l'os", "Se rompió un hueso de la mano.", "Cuerpo"],
  ["la ceja", "le sourcil", "Levantó una ceja, sorprendido.", "Cuerpo"],
  ["el labio", "la lèvre", "Tengo los labios secos.", "Cuerpo"],
  ["la frente", "le front (du visage)", "Le puse la mano en la frente: tenía fiebre.", "Cuerpo", "El frente = le front (militaire, météo)."],
  ["la mejilla", "la joue", "Le dio un beso en la mejilla.", "Cuerpo"],
  ["doler", "faire mal", "Me duele la cabeza.", "Cuerpo", "Se construit comme gustar : me duelen los pies. o→ue."],

  // --- Acciones : les gestes ---
  ["golpear", "frapper, cogner", "El boxeador golpeó a su rival en la mandíbula.", "Acciones", "Frapper une personne (la battre) : pegar. Frapper à la porte : llamar a la puerta."],
  ["pegar", "frapper (qqn) ; coller", "¡Mamá, mi hermano me ha pegado! / Pega la foto aquí.", "Acciones", "Deux sens très courants : frapper quelqu'un, et coller."],
  ["llamar a la puerta", "frapper à la porte", "Alguien está llamando a la puerta.", "Acciones", "En Espagne : llamar a la puerta (en Amérique : tocar la puerta)."],
  ["el golpe", "le coup", "Se dio un golpe en la cabeza.", "Acciones", "Darse un golpe = se cogner."],
  ["el puño", "le poing", "Golpeó la mesa con el puño.", "Acciones"],
  ["dar una patada", "donner un coup de pied", "Le dio una patada al balón.", "Acciones"],
  ["la bofetada", "la gifle", "Le dio una bofetada delante de todos.", "Acciones"],
  ["empujar", "pousser", "No empujes, hay sitio para todos.", "Acciones", "Sur les portes : EMPUJAR (pousser) / TIRAR (tirer)."],
  ["tirar", "jeter ; tirer", "Tira la basura al salir. / Tira de la cuerda.", "Acciones", "tirar algo = jeter ; tirar DE algo = tirer sur."],
  ["lanzar", "lancer", "Lanzó la pelota muy lejos.", "Acciones"],
  ["coger", "prendre, attraper", "Cojo el metro todos los días.", "Acciones", "Neutre en Espagne. En Amérique latine, vulgaire : on dit tomar / agarrar."],
  ["agarrar", "saisir, empoigner", "Agárrate a la barra, que el autobús frena.", "Acciones"],
  ["soltar", "lâcher", "¡Suelta eso ahora mismo!", "Acciones", "o→ue : suelto, sueltas."],
  ["romper", "casser", "He roto un vaso sin querer.", "Acciones", "Participe irrégulier : roto. Romper con alguien = rompre avec quelqu'un."],
  ["caerse", "tomber", "Me caí de la bici.", "Acciones", "Yo me caigo. Caer bien / mal = être sympathique / antipathique."],
  ["levantar", "lever, soulever", "Levanta la mano si sabes la respuesta.", "Acciones", "Levantarse = se lever."],
  ["saltar", "sauter", "El gato saltó por la ventana.", "Acciones"],
  ["correr", "courir", "Salgo a correr tres veces por semana.", "Acciones"],
  ["caminar", "marcher", "Me gusta caminar por la playa.", "Acciones", "Aussi andar. El reloj no anda = la montre ne marche pas."],
  ["bajar", "descendre ; baisser", "Bajamos en la próxima parada. / Baja la voz.", "Acciones"],
  ["abrir", "ouvrir", "¿Puedes abrir la ventana?", "Acciones", "Participe irrégulier : abierto."],
  ["cerrar", "fermer", "Cierra la puerta, por favor.", "Acciones", "e→ie : cierro, cierras."],
  ["encender", "allumer", "Enciende la luz, que no veo nada.", "Acciones", "e→ie : enciendo. Contraire : apagar."],
  ["apagar", "éteindre", "Apaga el móvil durante la película.", "Acciones"],
  ["tocar", "toucher ; jouer (d'un instrument)", "No toques eso. / Toco la guitarra desde los doce años.", "Acciones", "Instrument = TOCAR ; jeu ou sport = JUGAR. Te toca = c'est ton tour."],
  ["jugar", "jouer (jeu, sport)", "Jugamos al fútbol los domingos.", "Acciones", "jugar A + article : jugar al tenis. u→ue : juego."],
  ["gritar", "crier", "No me grites.", "Acciones"],
  ["llorar", "pleurer", "El bebé no deja de llorar.", "Acciones"],
  ["reírse", "rire", "Nos reímos mucho con él.", "Acciones", "reírse DE = se moquer de."],
  ["sonreír", "sourire", "Sonríe, que te hago una foto.", "Acciones"],
  ["besar", "embrasser (donner un baiser)", "Me besó en la mejilla.", "Acciones", "Un beso = un baiser, une bise. Serrer dans ses bras = abrazar."],
  ["abrazar", "serrer dans ses bras", "Me abrazó muy fuerte.", "Acciones", "Un abrazo = une accolade ; en fin de message : « Un abrazo »."],
  ["morder", "mordre", "El perro le mordió la pierna.", "Acciones", "o→ue : muerdo."],
  ["cortar", "couper", "Corta el pan, por favor.", "Acciones", "Cortarse el pelo = se faire couper les cheveux."],
  ["atar", "attacher, nouer", "Átate los cordones.", "Acciones"],
  ["esconder", "cacher", "Escondió el regalo en el armario.", "Acciones"],
  ["encontrar", "trouver", "No encuentro mi móvil.", "Acciones", "o→ue. Encontrarse con alguien = tomber sur quelqu'un."],
  ["perder", "perdre ; rater", "He perdido las llaves. / Perdí el tren.", "Acciones", "Rater un train = perder el tren."],
  ["ganar", "gagner", "Ganamos el partido. / Gana poco dinero.", "Acciones"],
  ["mover", "bouger, déplacer", "Ayúdame a mover el sofá.", "Acciones", "o→ue. Moverse = bouger (soi-même)."],
  ["sentarse", "s'asseoir", "Siéntate, por favor.", "Acciones", "e→ie : me siento. Estar sentado = être assis."],
  ["tumbarse", "s'allonger", "Me tumbé en el sofá.", "Acciones"],
  ["despertarse", "se réveiller", "Me despierto a las siete.", "Acciones", "e→ie. Despertar a alguien = réveiller quelqu'un."],
  ["dormirse", "s'endormir", "Me dormí viendo la película.", "Acciones"],
  ["ducharse", "se doucher", "Me ducho por la mañana.", "Acciones"],
  ["lavar", "laver", "Tengo que lavar el coche.", "Acciones", "Lavarse las manos = se laver les mains."],
  ["limpiar", "nettoyer", "Limpiamos la casa los sábados.", "Acciones"],
  ["cocinar", "cuisiner", "Me encanta cocinar para mis amigos.", "Acciones"],
  ["guardar", "garder ; ranger", "Guarda la ropa en el armario.", "Acciones", "Guardar un secreto = garder un secret."],
  ["meter", "mettre (dans)", "Mete la leche en la nevera.", "Acciones", "Meterse en = se mêler de."],
  ["sacar", "sortir (qqch) ; obtenir", "Saca la basura. / Saqué un ocho en el examen.", "Acciones", "Sacar una foto = prendre une photo."],
  ["echar", "jeter ; verser ; mettre", "Échale sal a la sopa.", "Acciones", "Echar de menos = manquer : te echo de menos."],
  ["llenar", "remplir", "Llena la botella de agua.", "Acciones", "Rellenar un formulario = remplir un formulaire."],
  ["colgar", "accrocher ; raccrocher", "Cuelga el abrigo aquí. / Me colgó el teléfono.", "Acciones", "o→ue : cuelgo."],
  ["dejar", "laisser ; prêter", "Deja las llaves en la mesa. / ¿Me dejas tu boli?", "Acciones", "Dejar de + infinitif = arrêter de."],
  ["pasar", "passer ; se passer", "¿Qué te pasa? / Pasa por mi casa.", "Acciones", "¿Qué pasa? = qu'est-ce qui se passe ?"],
  ["girar", "tourner", "Gira a la izquierda en el semáforo.", "Acciones"],
  ["oler", "sentir (une odeur)", "Huele a café. / Esto huele mal.", "Acciones", "o→ue avec h : huelo, hueles. Oler A = sentir le…"],
  ["oír", "entendre", "¿Me oyes bien?", "Acciones", "Oír = entendre ; escuchar = écouter."],
  ["mirar", "regarder", "Mira, allí está el museo.", "Acciones", "Mirar = regarder ; ver = voir."],

  // --- Casa & mesa ---
  ["la puerta", "la porte", "Cierra la puerta con llave.", "Casa"],
  ["la pared", "le mur", "Colgamos el cuadro en la pared.", "Casa", "El muro = mur extérieur, muraille."],
  ["la cama", "le lit", "Todavía estoy en la cama.", "Casa", "Hacer la cama = faire son lit."],
  ["el espejo", "le miroir", "Se miró en el espejo.", "Casa"],
  ["el baño", "la salle de bain ; les toilettes", "¿Dónde está el baño?", "Casa"],
  ["la ducha", "la douche", "Estoy en la ducha.", "Casa"],
  ["la bañera", "la baignoire", "Prefiero la ducha a la bañera.", "Casa"],
  ["el jardín", "le jardin", "Mi abuelo cultiva tomates en el jardín.", "Casa"],
  ["la estantería", "l'étagère", "Pon los libros en la estantería.", "Casa"],
  ["la toalla", "la serviette (de bain)", "No te olvides la toalla para la playa.", "Casa", "Serviette de table = la servilleta."],
  ["el jabón", "le savon", "Lávate las manos con jabón.", "Casa"],
  ["el cepillo de dientes", "la brosse à dents", "Se me ha olvidado el cepillo de dientes.", "Casa"],
  ["la cortina", "le rideau", "Cierra las cortinas.", "Casa"],
  ["el horno", "le four", "Mete el pollo en el horno.", "Casa"],
  ["el microondas", "le micro-ondes", "Calienta la leche en el microondas.", "Casa"],
  ["la luz", "la lumière ; le courant", "Apaga la luz. / Se ha ido la luz.", "Casa", "Se ha ido la luz = il y a une coupure de courant."],
  ["el ascensor", "l'ascenseur", "El ascensor no funciona.", "Casa"],
  ["el cuchillo", "le couteau", "Este cuchillo no corta.", "Casa"],
  ["el tenedor", "la fourchette", "¿Me pasas un tenedor?", "Casa"],
  ["la cuchara", "la cuillère", "La sopa se come con cuchara.", "Casa", "La cucharilla = la petite cuillère."],
  ["el plato", "l'assiette ; le plat", "Pon los platos en la mesa. / El plato del día.", "Casa", "Fregar los platos = faire la vaisselle."],
  ["la taza", "la tasse", "Me tomo una taza de café.", "Casa"],
  ["la botella", "la bouteille", "Una botella de vino tinto.", "Casa"],
  ["la servilleta", "la serviette (de table)", "¿Me pasas una servilleta?", "Casa"],
  ["el mantel", "la nappe", "Pon el mantel, que vamos a comer.", "Casa"],

  // --- Comida ---
  ["el agua", "l'eau", "Una botella de agua fría.", "Comida", "Féminin, mais EL devant le a tonique : el agua fría, las aguas."],
  ["la leche", "le lait", "Tomo el café con leche.", "Comida", "Féminin : la leche."],
  ["el arroz", "le riz", "La paella se hace con arroz.", "Comida"],
  ["el pollo", "le poulet", "Pollo asado con patatas.", "Comida"],
  ["la patata", "la pomme de terre", "Una tortilla de patatas.", "Comida", "Espagne : patata ; Amérique latine : papa."],
  ["el tomate", "la tomate", "Pan con tomate y aceite.", "Comida", "Masculin : el tomate."],
  ["la manzana", "la pomme", "Me como una manzana al día.", "Comida"],
  ["el plátano", "la banane", "Un plátano antes de entrenar.", "Comida"],
  ["la naranja", "l'orange (fruit)", "Un zumo de naranja natural.", "Comida"],
  ["la fresa", "la fraise", "Fresas con nata.", "Comida"],
  ["el limón", "le citron", "Agua con limón.", "Comida"],
  ["la uva", "le raisin", "En Nochevieja se comen doce uvas.", "Comida", "Una uva = un grain de raisin."],
  ["el melocotón", "la pêche (fruit)", "Los melocotones de verano son los mejores.", "Comida"],
  ["la zanahoria", "la carotte", "Pela las zanahorias.", "Comida"],
  ["la lechuga", "la laitue", "Una ensalada de lechuga y tomate.", "Comida", "La ensalada = le plat ; la lechuga = la plante."],
  ["las judías verdes", "les haricots verts", "Judías verdes con patatas.", "Comida"],
  ["los garbanzos", "les pois chiches", "El cocido lleva garbanzos.", "Comida"],
  ["las lentejas", "les lentilles", "Mi madre hace unas lentejas buenísimas.", "Comida"],
  ["la sal", "le sel", "A la sopa le falta sal.", "Comida", "Féminin : la sal."],
  ["la pimienta", "le poivre", "Sal y pimienta al gusto.", "Comida", "El pimiento = le poivron."],
  ["la mantequilla", "le beurre", "Tostadas con mantequilla y mermelada.", "Comida"],
  ["el zumo", "le jus", "Un zumo de naranja, por favor.", "Comida", "Espagne : zumo ; Amérique latine : jugo."],
  ["la galleta", "le biscuit", "Galletas con leche para merendar.", "Comida"],
  ["el pastel", "le gâteau", "Un pastel de cumpleaños.", "Comida", "Aussi la tarta."],
  ["el helado", "la glace (dessert)", "Un helado de chocolate.", "Comida", "La glace (eau gelée) = el hielo."],
  ["el jamón", "le jambon", "Un bocadillo de jamón.", "Comida"],

  // --- Tiempo & calendario ---
  ["la noche", "la nuit ; le soir", "Llegué a las diez de la noche.", "Tiempo", "Esta noche = ce soir."],
  ["la madrugada", "le petit matin (après minuit)", "Volvimos a las tres de la madrugada.", "Tiempo"],
  ["el mediodía", "midi", "Comemos al mediodía.", "Tiempo"],
  ["la hora", "l'heure", "¿Qué hora es?", "Tiempo", "¿A qué hora…? = À quelle heure… ?"],
  ["el mes", "le mois", "El mes que viene me voy de viaje.", "Tiempo"],
  ["el año", "l'année, l'an", "El año pasado estuve en México.", "Tiempo", "Le tilde compte : año (an) ≠ ano."],
  ["anoche", "hier soir", "Anoche dormí fatal.", "Tiempo"],
  ["anteayer", "avant-hier", "Anteayer fue mi cumpleaños.", "Tiempo"],
  ["pasado mañana", "après-demain", "Nos vemos pasado mañana.", "Tiempo"],
  ["la semana que viene", "la semaine prochaine", "La semana que viene tengo exámenes.", "Tiempo", "Aussi la próxima semana."],
  ["dentro de", "dans (+ durée à venir)", "Vuelvo dentro de diez minutos.", "Tiempo", "Il y a (+ durée passée) = hace : hace diez minutos."],
  ["hace dos días", "il y a deux jours", "Llegué hace dos días.", "Tiempo", "hace + durée = il y a. Desde hace = depuis."],
  ["todavía", "encore ; toujours", "Todavía no he terminado. / ¿Todavía vives allí?", "Tiempo", "Todavía no = pas encore ; ya = déjà."],
  ["ya", "déjà ; maintenant", "Ya he comido. / ¡Ya voy!", "Tiempo", "Ya no = ne… plus : ya no fumo."],
  ["pronto", "tôt ; bientôt", "Hoy he llegado pronto. / ¡Hasta pronto!", "Tiempo", "En Espagne, pronto = tôt (llegar pronto) ET bientôt."],
  ["la primavera", "le printemps", "En primavera florecen los almendros.", "Tiempo"],
  ["el verano", "l'été", "Este verano vamos a la playa.", "Tiempo"],
  ["el otoño", "l'automne", "En otoño caen las hojas.", "Tiempo"],
  ["el invierno", "l'hiver", "En invierno anochece muy pronto.", "Tiempo"],
  ["la nieve", "la neige", "Hay nieve en la sierra.", "Tiempo", "Nevar = neiger : está nevando."],
  ["el viento", "le vent", "Hace mucho viento.", "Tiempo", "Hace viento / hace sol / hace calor."],
  ["hace calor", "il fait chaud", "En agosto hace muchísimo calor.", "Tiempo", "Hace calor (la météo) / tengo calor (moi) / está caliente (un objet)."],
  ["hace buen tiempo", "il fait beau", "Si hace buen tiempo, vamos a la playa.", "Tiempo"],
  ["está nublado", "le ciel est couvert", "Hoy está nublado.", "Tiempo"],
  ["la tormenta", "l'orage, la tempête", "Anoche hubo una tormenta.", "Tiempo"],
  ["el hielo", "la glace (eau gelée)", "Un refresco con hielo.", "Tiempo"],

  // --- Dónde : se situer ---
  ["cerca de", "près de", "Vivo cerca de la estación.", "Dónde"],
  ["lejos de", "loin de", "El aeropuerto está lejos del centro.", "Dónde"],
  ["delante de", "devant", "Te espero delante del cine.", "Dónde"],
  ["detrás de", "derrière", "El parque está detrás de la iglesia.", "Dónde"],
  ["encima de", "sur, au-dessus de", "Las llaves están encima de la mesa.", "Dónde"],
  ["debajo de", "sous", "El gato está debajo de la cama.", "Dónde"],
  ["al lado de", "à côté de", "Siéntate al lado de tu hermano.", "Dónde"],
  ["enfrente de", "en face de", "La farmacia está enfrente del banco.", "Dónde"],
  ["entre", "entre ; parmi", "Está entre el bar y la farmacia.", "Dónde", "Entre tú y yo (pas « entre ti y mí »)."],
  ["dentro", "dedans, à l'intérieur", "Hace frío, vamos dentro.", "Dónde"],
  ["fuera", "dehors", "Los niños juegan fuera.", "Dónde"],
  ["arriba", "en haut", "Mi habitación está arriba.", "Dónde"],
  ["abajo", "en bas", "Te espero abajo.", "Dónde"],
  ["a la derecha", "à droite", "El baño está a la derecha.", "Dónde"],
  ["a la izquierda", "à gauche", "Gira a la izquierda.", "Dónde"],
  ["todo recto", "tout droit", "Siga todo recto hasta la plaza.", "Dónde", "Tout droit = todo recto (pas « derecho » en Espagne)."],

  // --- Números ---
  ["la mitad", "la moitié", "Me comí la mitad de la pizza.", "Números"],
  ["el doble", "le double", "Cuesta el doble que el año pasado.", "Números"],
  ["cien", "cent", "Cien euros. / Ciento veinte euros.", "Números", "Cien seul ou devant un nom ; ciento + autre nombre : ciento veinte."],
  ["quinientos", "cinq cents", "Quinientos kilómetros.", "Números", "Irréguliers : quinientos, setecientos, novecientos."],
  ["mil", "mille", "Dos mil personas.", "Números", "Invariable : dos mil (jamais « dos miles »)."],
  ["un millón de", "un million de", "Un millón de habitantes.", "Números", "Un millón DE personas (avec de)."],
  ["la docena", "la douzaine", "Una docena de huevos.", "Números"],
  ["contar", "compter ; raconter", "Cuenta hasta diez. / Cuéntame qué pasó.", "Números", "o→ue : cuento, cuentas."],

  // --- Ciudad ---
  ["el banco", "la banque ; le banc", "Voy al banco a sacar dinero. / Nos sentamos en un banco.", "Ciudad"],
  ["la iglesia", "l'église", "La iglesia del pueblo es del siglo XII.", "Ciudad"],
  ["la estación", "la gare ; la saison", "La estación de tren está lejos.", "Ciudad"],
  ["el puente", "le pont", "Cruzamos el puente a pie.", "Ciudad", "Un puente = aussi un pont (jour férié + week-end)."],
  ["el edificio", "le bâtiment, l'immeuble", "Vivo en un edificio muy antiguo.", "Ciudad"],
  ["el colegio", "l'école", "Los niños van al colegio en autobús.", "Ciudad", "≠ collège. Le collège / lycée = el instituto."],
  ["Correos", "la Poste", "Tengo que ir a Correos a mandar un paquete.", "Ciudad"],

  // --- Objetos ---
  ["el paraguas", "le parapluie", "Coge el paraguas, que va a llover.", "Objetos", "Invariable : un paraguas, dos paraguas."],
  ["la cartera", "le portefeuille", "Me han robado la cartera.", "Objetos", "Aussi le cartable."],
  ["la caja", "la boîte ; la caisse", "Guarda las fotos en una caja. / Pague en caja.", "Objetos"],
  ["el bolígrafo", "le stylo (bille)", "¿Me dejas un bolígrafo?", "Objetos", "Familier : el boli."],
  ["el lápiz", "le crayon", "Escribe a lápiz.", "Objetos"],
  ["las tijeras", "les ciseaux", "¿Dónde están las tijeras?", "Objetos"],
  ["la cuerda", "la corde", "Ata la caja con una cuerda.", "Objetos"],
  ["el regalo", "le cadeau", "Es un regalo para ti.", "Objetos"],
  ["el juguete", "le jouet", "El niño tiene demasiados juguetes.", "Objetos"],
  ["la pelota", "la balle, le ballon", "Los niños juegan a la pelota.", "Objetos", "El balón = le ballon (foot, basket)."],
  ["el reloj", "la montre ; l'horloge", "Mi reloj va cinco minutos adelantado.", "Objetos"],
  ["el cargador", "le chargeur", "¿Tienes un cargador de móvil?", "Objetos"],
  ["la pila", "la pile", "El mando no funciona: cambia las pilas.", "Objetos"],

  // --- Adjetivos básicos ---
  ["grande", "grand", "Una casa grande. / Un gran día.", "Adjetivos", "Devant un nom singulier : gran (un gran amigo)."],
  ["pequeño", "petit", "Un piso pequeño.", "Adjetivos", "Hermano pequeño = petit frère."],
  ["alto", "grand (de taille) ; haut", "Mi hermano es muy alto.", "Adjetivos", "Pour la taille d'une personne : alto / bajo."],
  ["bajo", "petit (de taille) ; bas", "Es bajito pero muy fuerte.", "Adjetivos"],
  ["ancho", "large", "Una calle muy ancha.", "Adjetivos"],
  ["corto", "court", "Tiene el pelo corto.", "Adjetivos"],
  ["gordo", "gros", "El gato está muy gordo.", "Adjetivos", "El Gordo = le gros lot de la loterie de Noël."],
  ["delgado", "mince", "Está más delgado que antes.", "Adjetivos"],
  ["nuevo", "neuf ; nouveau", "Tengo un móvil nuevo.", "Adjetivos"],
  ["viejo", "vieux", "Este coche ya es muy viejo.", "Adjetivos", "Pour une personne, plus poli : mayor."],
  ["antiguo", "ancien", "Un edificio antiguo.", "Adjetivos"],
  ["limpio", "propre", "La cocina está limpia.", "Adjetivos"],
  ["sucio", "sale", "Tienes las manos sucias.", "Adjetivos"],
  ["caliente", "chaud (objet)", "Cuidado, el plato está caliente.", "Adjetivos", "Pour la météo : hace calor ; pour soi : tengo calor."],
  ["frío", "froid", "El café se ha quedado frío.", "Adjetivos"],
  ["mojado", "mouillé", "Tengo los zapatos mojados.", "Adjetivos"],
  ["seco", "sec", "Es un clima muy seco.", "Adjetivos"],
  ["vacío", "vide", "La nevera está vacía.", "Adjetivos"],
  ["duro", "dur", "El pan está duro.", "Adjetivos"],
  ["blando", "mou", "Este colchón es demasiado blando.", "Adjetivos"],
  ["suave", "doux (au toucher)", "Esta toalla es muy suave.", "Adjetivos"],
  ["dulce", "sucré ; doux", "No me gusta el café tan dulce.", "Adjetivos"],
  ["salado", "salé", "La sopa está muy salada.", "Adjetivos"],
  ["amargo", "amer", "El café solo es amargo.", "Adjetivos"],
  ["feliz", "heureux", "Soy muy feliz aquí.", "Adjetivos", "Invariable en genre ; pluriel : felices."],
  ["enfermo", "malade", "Estoy enfermo, no puedo ir.", "Adjetivos"],
  ["tonto", "bête, idiot", "No seas tonto.", "Adjetivos"],
  ["guapo", "beau (personne)", "Tu hermano es muy guapo.", "Adjetivos"],
  ["peligroso", "dangereux", "Es peligroso nadar aquí.", "Adjetivos"],
  ["ruidoso", "bruyant", "El bar de abajo es muy ruidoso.", "Adjetivos"],
  ["tranquilo", "calme, tranquille", "Vivo en un barrio muy tranquilo.", "Adjetivos"],

  // --- Verbos de base ---
  ["enseñar", "enseigner ; montrer", "Te enseño mi casa. / Enseña matemáticas.", "Verbos"],
  ["aprender", "apprendre", "Estoy aprendiendo a nadar.", "Verbos", "aprender A + infinitif."],
  ["llegar", "arriver", "El tren llega a las nueve.", "Verbos", "llegar A un lugar (jamais « en »)."],
  ["salir", "sortir ; partir", "Salgo de casa a las ocho.", "Verbos", "Yo salgo. Salir con alguien = sortir avec quelqu'un."],
  ["volver", "revenir, rentrer", "Vuelvo a casa tarde.", "Verbos", "o→ue. Volver a + infinitif = refaire."],
  ["entender", "comprendre", "No te entiendo.", "Verbos", "e→ie : entiendo."],
  ["creer", "croire, penser", "Creo que tienes razón.", "Verbos"],
  ["pensar", "penser", "Pienso en ti. / Pienso ir mañana.", "Verbos", "pensar EN = penser à ; pensar + infinitif = compter faire."],
  ["sentir", "sentir ; regretter", "Lo siento mucho.", "Verbos", "Lo siento = je suis désolé. Sentirse bien / mal = se sentir bien / mal."],
  ["necesitar", "avoir besoin de", "Necesito ayuda.", "Verbos", "Sans préposition : necesito un coche."],
  ["elegir", "choisir", "Elige el que quieras.", "Verbos", "e→i et g→j : elijo, eliges."],
  ["cambiar", "changer", "He cambiado de opinión.", "Verbos", "cambiar DE + nom : cambiar de trabajo."],
  ["enviar", "envoyer", "Te envío el archivo por correo.", "Verbos"],
  ["recordar", "se rappeler ; rappeler", "No recuerdo su nombre. / Recuérdame que llame.", "Verbos", "o→ue. Sans préposition (≠ acordarse DE)."],
  ["usar", "utiliser", "¿Sabes usar esta máquina?", "Verbos"],
  ["pagar", "payer", "¿Puedo pagar con tarjeta?", "Verbos", "Pagar algo, sans préposition : pagar la cuenta."],
  ["costar", "coûter", "¿Cuánto cuesta?", "Verbos", "o→ue : cuesta, cuestan."],
  ["nadar", "nager", "Aprendí a nadar de pequeño.", "Verbos"],
  ["cantar", "chanter", "Canta en un coro.", "Verbos"],
  ["bailar", "danser", "¿Bailamos?", "Verbos"]

]);
