/* ============================================================
   CUMBRE — Vocabulaire espagnol (thèmes élargis + faux-amis + erreurs fréquentes)
   [ES, FR, exemple ES, thème]
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  // --- Verbes (plus) ---
  ["acordarse de", "se souvenir de", "No me acuerdo de su nombre.", "Verbos"],
  ["darse cuenta de", "se rendre compte de", "Me di cuenta del error.", "Verbos"],
  ["ponerse a", "se mettre à", "Se puso a llover de repente.", "Verbos"],
  ["dejar de", "arrêter de", "Dejé de fumar hace un año.", "Verbos"],
  ["volver a", "refaire, recommencer à", "Vuelve a intentarlo.", "Verbos"],
  ["soler", "avoir l'habitude de", "Suelo desayunar a las ocho.", "Verbos"],
  ["atreverse a", "oser", "No me atrevo a decírselo.", "Verbos"],
  ["quejarse de", "se plaindre de", "Se queja de todo.", "Verbos"],
  ["parecer", "sembler, paraître", "Parece cansado hoy.", "Verbos"],
  ["apoyar", "soutenir, appuyer", "Te apoyo en tu decisión.", "Verbos"],
  ["lograr", "parvenir à, réussir", "Logró terminar a tiempo.", "Verbos"],
  ["mejorar", "améliorer, s'améliorer", "Quiero mejorar mi español.", "Verbos"],
  ["aprovechar", "profiter de", "Aprovecha el buen tiempo.", "Verbos"],
  ["enterarse de", "apprendre, être au courant de", "Me enteré por la prensa.", "Verbos"],
  ["arreglar", "réparer, arranger", "Hay que arreglar el coche.", "Verbos"],
  ["tardar", "mettre du temps, tarder", "El tren tarda dos horas.", "Verbos"],

  // --- Corps & santé ---
  ["la cabeza", "la tête", "Me duele la cabeza.", "Cuerpo"],
  ["la mano", "la main", "Levanta la mano.", "Cuerpo"],
  ["el brazo", "le bras", "Se rompió el brazo.", "Cuerpo"],
  ["la pierna", "la jambe", "Me duele la pierna izquierda.", "Cuerpo"],
  ["la espalda", "le dos", "Tengo dolor de espalda.", "Cuerpo"],
  ["el ojo", "l'œil", "Tiene los ojos verdes.", "Cuerpo"],
  ["la garganta", "la gorge", "Me duele la garganta.", "Cuerpo"],
  ["la muela", "la dent (molaire)", "Me duele una muela.", "Cuerpo"],
  ["la fiebre", "la fièvre", "Tiene fiebre alta.", "Cuerpo"],
  ["el resfriado", "le rhume", "Cogió un resfriado.", "Cuerpo"],
  ["la receta", "l'ordonnance ; la recette", "El médico me dio una receta.", "Cuerpo"],
  ["sano", "sain, en bonne santé", "Lleva una vida sana.", "Cuerpo"],

  // --- Voyages ---
  ["el viaje", "le voyage", "El viaje fue muy largo.", "Viajes"],
  ["el vuelo", "le vol", "El vuelo sale a las seis.", "Viajes"],
  ["la maleta", "la valise", "Hago la maleta esta noche.", "Viajes"],
  ["el equipaje", "les bagages", "El equipaje pesa mucho.", "Viajes"],
  ["el alojamiento", "l'hébergement", "El alojamiento está incluido.", "Viajes"],
  ["la aduana", "la douane", "Pasamos la aduana rápido.", "Viajes"],
  ["el retraso", "le retard", "El tren lleva retraso.", "Viajes"],
  ["reservar", "réserver", "Reservé una mesa para dos.", "Viajes"],
  ["el destino", "la destination", "¿Cuál es tu destino?", "Viajes"],
  ["la frontera", "la frontière", "Cruzamos la frontera de noche.", "Viajes"],

  // --- Nature & météo ---
  ["el árbol", "l'arbre", "El árbol da mucha sombra.", "Naturaleza"],
  ["el bosque", "la forêt", "Dimos un paseo por el bosque.", "Naturaleza"],
  ["el río", "la rivière, le fleuve", "El río pasa por la ciudad.", "Naturaleza"],
  ["la montaña", "la montagne", "Subimos a la montaña.", "Naturaleza"],
  ["la playa", "la plage", "La playa está llena de gente.", "Naturaleza"],
  ["la ola", "la vague", "Las olas son muy grandes.", "Naturaleza"],
  ["la niebla", "le brouillard", "Hay mucha niebla esta mañana.", "Naturaleza"],
  ["el trueno", "le tonnerre", "El trueno asustó al perro.", "Naturaleza"],
  ["el paisaje", "le paysage", "El paisaje es impresionante.", "Naturaleza"],
  ["la arena", "le sable", "La arena está caliente.", "Naturaleza"],

  // --- Émotions & caractère ---
  ["la alegría", "la joie", "Sentí una gran alegría.", "Emociones"],
  ["el miedo", "la peur", "Le da miedo la oscuridad.", "Emociones"],
  ["el enfado", "la colère", "Se le pasó el enfado.", "Emociones"],
  ["la vergüenza", "la honte, la gêne", "Me da vergüenza hablar en público.", "Emociones"],
  ["el orgullo", "la fierté, l'orgueil", "Lo dice con orgullo.", "Emociones"],
  ["los celos", "la jalousie", "Tiene celos de su hermano.", "Emociones"],
  ["el ánimo", "le moral, l'entrain", "¡Ánimo, tú puedes!", "Emociones"],
  ["amable", "aimable, gentil", "El camarero fue muy amable.", "Emociones"],
  ["testarudo", "têtu", "Es demasiado testarudo.", "Emociones"],
  ["tímido", "timide", "De niño era muy tímido.", "Emociones"],
  ["majo", "sympa (fam.)", "Tu hermano es muy majo.", "Emociones"],
  ["harto", "qui en a marre", "Estoy harto de esperar.", "Emociones"],

  // --- Adjectifs (plus) ---
  ["listo", "prêt (estar) ; malin (ser)", "Ya estoy listo para salir.", "Adjetivos"],
  ["amplio", "spacieux, ample", "El salón es muy amplio.", "Adjetivos"],
  ["estrecho", "étroit", "La calle es muy estrecha.", "Adjetivos"],
  ["profundo", "profond", "Es un tema profundo.", "Adjetivos"],
  ["ligero", "léger", "Tomé una cena ligera.", "Adjetivos"],
  ["pesado", "lourd ; pénible", "Este libro es muy pesado.", "Adjetivos"],
  ["sencillo", "simple", "Es una receta sencilla.", "Adjetivos"],
  ["raro", "bizarre, rare", "Qué raro, no contesta.", "Adjetivos"],
  ["imprescindible", "indispensable", "El pasaporte es imprescindible.", "Adjetivos"],
  ["cotidiano", "quotidien", "Forma parte de la vida cotidiana.", "Adjetivos"],

  // --- Connecteurs & expressions utiles ---
  ["sin embargo", "cependant, néanmoins", "Es caro; sin embargo, vale la pena.", "Conectores"],
  ["por lo tanto", "par conséquent", "Llueve, por lo tanto no salimos.", "Conectores"],
  ["además", "de plus, en outre", "Es tarde y, además, estoy cansado.", "Conectores"],
  ["a pesar de", "malgré", "Vino a pesar de la lluvia.", "Conectores"],
  ["en cuanto", "dès que", "Te llamo en cuanto llegue.", "Conectores"],
  ["mientras tanto", "pendant ce temps", "Tú cocina; mientras tanto, pongo la mesa.", "Conectores"],
  ["de hecho", "en fait, de fait", "De hecho, ya lo sabía.", "Conectores"],
  ["o sea", "c'est-à-dire", "Llega tarde, o sea, como siempre.", "Conectores"],
  ["en seguida", "tout de suite", "Vuelvo en seguida.", "Conectores"],
  ["a lo mejor", "peut-être", "A lo mejor viene esta noche.", "Conectores"],
  ["por cierto", "au fait, à propos", "Por cierto, ¿cómo está tu madre?", "Conectores"],
  ["de repente", "soudain", "De repente se apagó la luz.", "Conectores"],

  // --- Faux-amis (attention au sens !) ---
  ["embarazada", "enceinte (≠ embarrassée = avergonzada)", "Mi hermana está embarazada.", "Falsos amigos"],
  ["el éxito", "le succès (≠ sortie = la salida)", "La obra fue todo un éxito.", "Falsos amigos"],
  ["largo", "long (≠ large = ancho)", "Es un camino muy largo.", "Falsos amigos"],
  ["constipado", "enrhumé (≠ constipé = estreñido)", "Estoy constipado, tengo mocos.", "Falsos amigos"],
  ["sensible", "sensible/émotif (≠ sensé = sensato)", "Es una persona muy sensible.", "Falsos amigos"],
  ["discutir", "se disputer (≠ discuter = hablar, charlar)", "Discutieron por dinero.", "Falsos amigos"],
  ["asistir a", "assister à (≠ aider = ayudar)", "Asistí a la conferencia.", "Falsos amigos"],
  ["quitar", "enlever, retirer (≠ quitter = dejar, salir)", "Quítate el abrigo.", "Falsos amigos"],
  ["subir", "monter (≠ subir = sufrir)", "Sube al segundo piso.", "Falsos amigos"],
  ["realizar", "réaliser, effectuer (≠ se rendre compte = darse cuenta)", "Realizó un gran trabajo.", "Falsos amigos"],
  ["actualmente", "actuellement (≠ en fait = de hecho)", "Actualmente vivo en Lyon.", "Falsos amigos"],
  ["la carta", "la lettre ; le menu (≠ carte = el mapa, la tarjeta)", "Te escribí una carta.", "Falsos amigos"],
  ["el gato", "le chat (≠ gâteau = el pastel)", "El gato duerme en el sofá.", "Falsos amigos"],
  ["nombre", "prénom, nom (≠ nombre = número)", "¿Cuál es tu nombre?", "Falsos amigos"],

  // --- Erreurs fréquentes (francophones) : toujours la BONNE forme ---
  ["tener ... años", "avoir ... ans (jamais ser/estar)", "Tengo veintidós años.", "Errores frecuentes"],
  ["hay que + infinitivo", "il faut (+ infinitif)", "Hay que estudiar más.", "Errores frecuentes"],
  ["tener que + infinitivo", "devoir (+ infinitif)", "Tengo que irme ya.", "Errores frecuentes"],
  ["hace dos años", "il y a deux ans", "Nos conocimos hace dos años.", "Errores frecuentes"],
  ["desde hace un año", "depuis un an", "Vivo aquí desde hace un año.", "Errores frecuentes"],
  ["por la mañana", "le matin", "Estudio por la mañana.", "Errores frecuentes"],
  ["muy + adjetivo", "très (+ adjectif)", "Está muy cansado.", "Errores frecuentes"],
  ["mucho + sustantivo", "beaucoup de (+ nom)", "Tengo mucho trabajo.", "Errores frecuentes"],
  ["buscar (sin preposición)", "chercher (sans 'à/pour')", "Busco un piso céntrico.", "Errores frecuentes"],
  ["escuchar (sin preposición)", "écouter (sans 'à')", "Escucho música clásica.", "Errores frecuentes"],
  ["esperar (sin preposición)", "attendre (sans 'pour')", "Espero el autobús.", "Errores frecuentes"],
  ["pensar en", "penser à", "Pienso en ti.", "Errores frecuentes"],
  ["soñar con", "rêver de", "Sueño con viajar.", "Errores frecuentes"],
  ["casarse con", "se marier avec", "Se casó con una española.", "Errores frecuentes"],
  ["ver a alguien", "voir quelqu'un (a personnel)", "Vi a María en el metro.", "Errores frecuentes"],
  ["no ... nada", "ne ... rien (double négation)", "No tengo nada que hacer.", "Errores frecuentes"],
  ["no ... nadie", "ne ... personne", "No viene nadie a la reunión.", "Errores frecuentes"],
  ["el problema", "le problème (masc. malgré -a)", "El problema es muy grave.", "Errores frecuentes"],
  ["el día", "le jour (masc. malgré -a)", "Hace un día precioso.", "Errores frecuentes"],
  ["el idioma", "la langue (masc. malgré -a)", "El español es un idioma bonito.", "Errores frecuentes"],
  ["la mano", "la main (fém. malgré -o)", "Levanta la mano derecha.", "Errores frecuentes"],
  ["todo el mundo", "tout le monde (verbe au singulier)", "Todo el mundo está aquí.", "Errores frecuentes"],
  ["me gusta + infinitivo", "j'aime (+ infinitif)", "Me gusta leer por la noche.", "Errores frecuentes"],
  ["acabar de + infinitivo", "venir de (faire)", "Acabo de llegar.", "Errores frecuentes"]

]);
